//! Lookup table constants and bounds.
//!
//! The LUT is generated by `backend/curve/src/bin/lutgen.rs`.

use crate::lut::{S_LUT, X_LUT};

/// Number of curve point samples in the LUT.
pub(crate) const LUT_SIZE: usize = X_LUT.len();
/// Maximum cumulative cost in the LUT (Q16.48, as u64).
pub const LUT_S_MAX: u64 = S_LUT[LUT_SIZE - 1];
/// Minimum x value in the LUT (Q8.24, as u32).
pub const LUT_X_MIN: u32 = X_LUT[0];
/// Maximum x value in the LUT (Q8.24, as u32).
pub const LUT_X_MAX: u32 = X_LUT[LUT_SIZE - 1];
