//! Lookup table for the cumulative cost curve used by the curve crate.
//!
//! Values are stored as fixed-point numbers:
//! - `x` uses Q16.16
//! - `s` uses Q16.48
//!
//! `evaluate_cost` expects inputs to be within the LUT domain and performs
//! linear interpolation between the surrounding samples.
//!
//! The LUT is generated by `backend/curve/src/bin/lutgen.rs`.

/// Linearly interpolate `s` between two LUT samples at `x`.
#[inline]
fn interpolate_cost(x: i32, cp0: CostLutPoint, cp1: CostLutPoint) -> u64 {
    let dx = (cp1.x as i64 - cp0.x as i64) as i128;
    debug_assert!(dx != 0, "LUT points must have distinct x values");
    let t = (x as i64 - cp0.x as i64) as i128;

    let s0i = cp0.s as i128;
    let s1i = cp1.s as i128;

    let out = s0i + ((s1i - s0i) * t) / dx;
    out as u64
}

/// Linearly interpolate `x` between two LUT samples at cumulative cost `s`.
#[inline]
fn interpolate_x(s: u64, cp0: CostLutPoint, cp1: CostLutPoint) -> i32 {
    let ds = (cp1.s - cp0.s) as i128;
    debug_assert!(ds > 0, "LUT points must have distinct s values");
    let t = (s - cp0.s) as i128;

    let x0i = cp0.x as i128;
    let x1i = cp1.x as i128;

    let x = x0i + (t * (x1i - x0i) + ds / 2) / ds;
    x as i32
}

/// Evaluate the cumulative cost at `x` (Q16.16).
///
/// Callers must ensure `x` is within the LUT domain.
#[inline]
pub(crate) fn evaluate_cost(x: i32) -> u64 {
    let lo = COST_LUT[0].x;
    let hi = COST_LUT[COST_LUT.len() - 1].x;
    debug_assert!(
        x >= lo && x <= hi,
        "x must be within LUT domain: [{}, {}]",
        lo,
        hi
    );

    match COST_LUT.binary_search_by(|p| p.x.cmp(&x)) {
        Ok(i) => COST_LUT[i].s,
        Err(i) => {
            // x is between COST_LUT[i-1] and COST_LUT[i]
            // (since x is in-domain, i is in 1..len)
            debug_assert!(i > 0 && i < COST_LUT.len());
            let a = COST_LUT[i - 1];
            let b = COST_LUT[i];
            interpolate_cost(x, a, b)
        }
    }
}

/// Signed delta of cumulative cost (Q16.48) for moving from `x0` to `x0 + dx`.
/// `dx` may be negative and is applied with saturating arithmetic.
///
/// Callers must ensure `x0 + dx` stays within the LUT domain.
#[inline]
pub fn delta_cost_for_dx(x0: i32, dx: i32) -> i128 {
    let x1 = x0 + dx;
    debug_assert!(
        x1 >= COST_LUT[0].x && x1 <= COST_LUT[COST_LUT.len() - 1].x,
        "x0 + dx must be within the LUT domain"
    );
    evaluate_cost(x1) as i128 - evaluate_cost(x0) as i128
}

/// Solve for `dx` given `x0`, its cumulative cost `s0`, and a desired `ds`.
///
/// The mapping is computed by inverting the cumulative LUT with a binary search
/// on `s` and linear interpolation between samples. Callers must ensure inputs
/// are within the LUT domain.
#[inline]
pub fn dx_for_delta_cost(x0: i32, s0: i128, ds: i128) -> i32 {
    debug_assert!(
        x0 >= COST_LUT[0].x && x0 <= COST_LUT[COST_LUT.len() - 1].x,
        "x0 must be within LUT domain",
    );
    let s_target = s0 + ds;

    let x1 = invert_cost(s_target);
    x1 - x0
}

#[inline]
fn invert_cost(s_target: i128) -> i32 {
    let lo = COST_LUT[0];
    let hi = COST_LUT[COST_LUT.len() - 1];
    let s_min = lo.s as i128;
    let s_max = hi.s as i128;
    debug_assert!(
        s_target >= s_min && s_target <= s_max,
        "s must be within LUT range: [{}, {}]",
        s_min,
        s_max
    );

    let s_target_u64 = s_target as u64;
    match COST_LUT.binary_search_by(|p| p.s.cmp(&s_target_u64)) {
        Ok(i) => COST_LUT[i].x,
        Err(i) => {
            let a = COST_LUT[i - 1];
            let b = COST_LUT[i];
            interpolate_x(s_target_u64, a, b)
        }
    }
}

/// A master lookup-table of the cumulative cost curve.
#[derive(Copy, Clone)]
pub(crate) struct CostLutPoint {
    /// X-coordinate in Q16.16.
    pub(crate) x: i32,
    /// Cumulative cost value in Q16.48.
    pub(crate) s: u64,
}

/// Monotonic LUT samples across the supported x-domain.
pub(crate) static COST_LUT: [CostLutPoint; 1025] = [
    CostLutPoint { x: -393216, s: 0 },
    CostLutPoint {
        x: -391095,
        s: 22892197532,
    },
    CostLutPoint {
        x: -388984,
        s: 46422168089,
    },
    CostLutPoint {
        x: -386884,
        s: 70591697558,
    },
    CostLutPoint {
        x: -384794,
        s: 95425336864,
    },
    CostLutPoint {
        x: -382714,
        s: 120936795900,
    },
    CostLutPoint {
        x: -380645,
        s: 147127048534,
    },
    CostLutPoint {
        x: -378586,
        s: 174022085649,
    },
    CostLutPoint {
        x: -376538,
        s: 201622250263,
    },
    CostLutPoint {
        x: -374500,
        s: 229954505547,
    },
    CostLutPoint {
        x: -372471,
        s: 259047617073,
    },
    CostLutPoint {
        x: -370453,
        s: 288887215932,
    },
    CostLutPoint {
        x: -368445,
        s: 319501808471,
    },
    CostLutPoint {
        x: -366447,
        s: 350905864349,
    },
    CostLutPoint {
        x: -364459,
        s: 383113928566,
    },
    CostLutPoint {
        x: -362481,
        s: 416140614569,
    },
    CostLutPoint {
        x: -360512,
        s: 450018061063,
    },
    CostLutPoint {
        x: -358554,
        s: 484726596071,
    },
    CostLutPoint {
        x: -356605,
        s: 520316476042,
    },
    CostLutPoint {
        x: -354665,
        s: 556804176125,
    },
    CostLutPoint {
        x: -352736,
        s: 594166974380,
    },
    CostLutPoint {
        x: -350816,
        s: 632458544733,
    },
    CostLutPoint {
        x: -348906,
        s: 671674761753,
    },
    CostLutPoint {
        x: -347005,
        s: 711852032876,
    },
    CostLutPoint {
        x: -345113,
        s: 753007193723,
    },
    CostLutPoint {
        x: -343231,
        s: 795134449414,
    },
    CostLutPoint {
        x: -341359,
        s: 838248814359,
    },
    CostLutPoint {
        x: -339495,
        s: 882413330425,
    },
    CostLutPoint {
        x: -337641,
        s: 927597618904,
    },
    CostLutPoint {
        x: -335796,
        s: 973842077100,
    },
    CostLutPoint {
        x: -333961,
        s: 1021137640421,
    },
    CostLutPoint {
        x: -332134,
        s: 1069552938033,
    },
    CostLutPoint {
        x: -330317,
        s: 1119052042179,
    },
    CostLutPoint {
        x: -328508,
        s: 1169706537678,
    },
    CostLutPoint {
        x: -326709,
        s: 1221477493454,
    },
    CostLutPoint {
        x: -324918,
        s: 1274439545889,
    },
    CostLutPoint {
        x: -323137,
        s: 1328550584028,
    },
    CostLutPoint {
        x: -321364,
        s: 1383888393586,
    },
    CostLutPoint {
        x: -319600,
        s: 1440439989678,
    },
    CostLutPoint {
        x: -317845,
        s: 1498222304686,
    },
    CostLutPoint {
        x: -316099,
        s: 1557252202901,
    },
    CostLutPoint {
        x: -314361,
        s: 1617581639255,
    },
    CostLutPoint {
        x: -312632,
        s: 1679194000838,
    },
    CostLutPoint {
        x: -310912,
        s: 1742105935787,
    },
    CostLutPoint {
        x: -309200,
        s: 1806372003875,
    },
    CostLutPoint {
        x: -307497,
        s: 1871972568174,
    },
    CostLutPoint {
        x: -305802,
        s: 1938963986420,
    },
    CostLutPoint {
        x: -304115,
        s: 2007365532751,
    },
    CostLutPoint {
        x: -302437,
        s: 2077154321650,
    },
    CostLutPoint {
        x: -300767,
        s: 2148389504806,
    },
    CostLutPoint {
        x: -299106,
        s: 2221045845652,
    },
    CostLutPoint {
        x: -297453,
        s: 2295184381560,
    },
    CostLutPoint {
        x: -295808,
        s: 2370823942788,
    },
    CostLutPoint {
        x: -294171,
        s: 2447983260835,
    },
    CostLutPoint {
        x: -292543,
        s: 2526632050160,
    },
    CostLutPoint {
        x: -290922,
        s: 2606885409855,
    },
    CostLutPoint {
        x: -289310,
        s: 2688662632562,
    },
    CostLutPoint {
        x: -287705,
        s: 2772083372551,
    },
    CostLutPoint {
        x: -286109,
        s: 2857061676590,
    },
    CostLutPoint {
        x: -284521,
        s: 2943666697566,
    },
    CostLutPoint {
        x: -282940,
        s: 3031972570804,
    },
    CostLutPoint {
        x: -281367,
        s: 3121942893587,
    },
    CostLutPoint {
        x: -279802,
        s: 3213594934192,
    },
    CostLutPoint {
        x: -278245,
        s: 3306945730873,
    },
    CostLutPoint {
        x: -276696,
        s: 3402012077652,
    },
    CostLutPoint {
        x: -275154,
        s: 3498874056225,
    },
    CostLutPoint {
        x: -273620,
        s: 3597487345931,
    },
    CostLutPoint {
        x: -272094,
        s: 3697867999165,
    },
    CostLutPoint {
        x: -270575,
        s: 3800099838614,
    },
    CostLutPoint {
        x: -269064,
        s: 3904133348610,
    },
    CostLutPoint {
        x: -267560,
        s: 4010054934581,
    },
    CostLutPoint {
        x: -266064,
        s: 4117811439907,
    },
    CostLutPoint {
        x: -264576,
        s: 4227417418959,
    },
    CostLutPoint {
        x: -263094,
        s: 4339039363444,
    },
    CostLutPoint {
        x: -261620,
        s: 4452545543515,
    },
    CostLutPoint {
        x: -260154,
        s: 4567949502548,
    },
    CostLutPoint {
        x: -258694,
        s: 4685427052366,
    },
    CostLutPoint {
        x: -257242,
        s: 4804835327856,
    },
    CostLutPoint {
        x: -255797,
        s: 4926271676453,
    },
    CostLutPoint {
        x: -254360,
        s: 5049666765580,
    },
    CostLutPoint {
        x: -252929,
        s: 5175209465829,
    },
    CostLutPoint {
        x: -251506,
        s: 5302741078988,
    },
    CostLutPoint {
        x: -250089,
        s: 5432457316028,
    },
    CostLutPoint {
        x: -248680,
        s: 5564191161594,
    },
    CostLutPoint {
        x: -247278,
        s: 5698048871950,
    },
    CostLutPoint {
        x: -245883,
        s: 5834045741526,
    },
    CostLutPoint {
        x: -244494,
        s: 5972297232533,
    },
    CostLutPoint {
        x: -243113,
        s: 6112618785838,
    },
    CostLutPoint {
        x: -241738,
        s: 6255227743114,
    },
    CostLutPoint {
        x: -240371,
        s: 6399930308941,
    },
    CostLutPoint {
        x: -239010,
        s: 6546951415021,
    },
    CostLutPoint {
        x: -237656,
        s: 6696199056325,
    },
    CostLutPoint {
        x: -236308,
        s: 6847799111930,
    },
    CostLutPoint {
        x: -234967,
        s: 7001654341593,
    },
    CostLutPoint {
        x: -233633,
        s: 7157776107729,
    },
    CostLutPoint {
        x: -232306,
        s: 7316175239672,
    },
    CostLutPoint {
        x: -230985,
        s: 7476984946822,
    },
    CostLutPoint {
        x: -229671,
        s: 7640096850712,
    },
    CostLutPoint {
        x: -228363,
        s: 7805647986016,
    },
    CostLutPoint {
        x: -227062,
        s: 7973524167902,
    },
    CostLutPoint {
        x: -225767,
        s: 8143866333139,
    },
    CostLutPoint {
        x: -224479,
        s: 8316554297163,
    },
    CostLutPoint {
        x: -223197,
        s: 8491732976739,
    },
    CostLutPoint {
        x: -221922,
        s: 8669275993486,
    },
    CostLutPoint {
        x: -220653,
        s: 8849332323173,
    },
    CostLutPoint {
        x: -219390,
        s: 9031915110963,
    },
    CostLutPoint {
        x: -218133,
        s: 9217037013449,
    },
    CostLutPoint {
        x: -216883,
        s: 9404558781582,
    },
    CostLutPoint {
        x: -215639,
        s: 9594637860199,
    },
    CostLutPoint {
        x: -214401,
        s: 9787285250031,
    },
    CostLutPoint {
        x: -213170,
        s: 9982351507806,
    },
    CostLutPoint {
        x: -211944,
        s: 10180163428822,
    },
    CostLutPoint {
        x: -210724,
        s: 10380573310690,
    },
    CostLutPoint {
        x: -209511,
        s: 10583421177079,
    },
    CostLutPoint {
        x: -208304,
        s: 10788877872186,
    },
    CostLutPoint {
        x: -207102,
        s: 10997125602805,
    },
    CostLutPoint {
        x: -205907,
        s: 11207824698562,
    },
    CostLutPoint {
        x: -204717,
        s: 11421334042026,
    },
    CostLutPoint {
        x: -203534,
        s: 11637300338876,
    },
    CostLutPoint {
        x: -202356,
        s: 11856093641341,
    },
    CostLutPoint {
        x: -201184,
        s: 12077537254200,
    },
    CostLutPoint {
        x: -200018,
        s: 12301634778181,
    },
    CostLutPoint {
        x: -198858,
        s: 12528389114157,
    },
    CostLutPoint {
        x: -197704,
        s: 12757802451037,
    },
    CostLutPoint {
        x: -196555,
        s: 12990080101917,
    },
    CostLutPoint {
        x: -195412,
        s: 13225025771922,
    },
    CostLutPoint {
        x: -194275,
        s: 13462639550831,
    },
    CostLutPoint {
        x: -193144,
        s: 13702920769605,
    },
    CostLutPoint {
        x: -192018,
        s: 13946085708803,
    },
    CostLutPoint {
        x: -190897,
        s: 14192142826912,
    },
    CostLutPoint {
        x: -189782,
        s: 14440875129962,
    },
    CostLutPoint {
        x: -188673,
        s: 14692279016694,
    },
    CostLutPoint {
        x: -187570,
        s: 14946350072625,
    },
    CostLutPoint {
        x: -186471,
        s: 15203554843884,
    },
    CostLutPoint {
        x: -185379,
        s: 15463190806278,
    },
    CostLutPoint {
        x: -184291,
        s: 15725970174223,
    },
    CostLutPoint {
        x: -183209,
        s: 15991413711820,
    },
    CostLutPoint {
        x: -182133,
        s: 16259513104341,
    },
    CostLutPoint {
        x: -181062,
        s: 16530514150013,
    },
    CostLutPoint {
        x: -179996,
        s: 16804418560534,
    },
    CostLutPoint {
        x: -178935,
        s: 17081227375067,
    },
    CostLutPoint {
        x: -177880,
        s: 17360674065238,
    },
    CostLutPoint {
        x: -176830,
        s: 17643017101497,
    },
    CostLutPoint {
        x: -175785,
        s: 17928255337174,
    },
    CostLutPoint {
        x: -174746,
        s: 18216107808041,
    },
    CostLutPoint {
        x: -173711,
        s: 18507126009007,
    },
    CostLutPoint {
        x: -172682,
        s: 18800744204373,
    },
    CostLutPoint {
        x: -171658,
        s: 19097237360528,
    },
    CostLutPoint {
        x: -170639,
        s: 19396600593819,
    },
    CostLutPoint {
        x: -169625,
        s: 19698828271670,
    },
    CostLutPoint {
        x: -168616,
        s: 20003914005147,
    },
    CostLutPoint {
        x: -167612,
        s: 20311850641758,
    },
    CostLutPoint {
        x: -166613,
        s: 20622630258527,
    },
    CostLutPoint {
        x: -165619,
        s: 20936244155320,
    },
    CostLutPoint {
        x: -164630,
        s: 21252682848447,
    },
    CostLutPoint {
        x: -163646,
        s: 21571936064534,
    },
    CostLutPoint {
        x: -162667,
        s: 21893992734687,
    },
    CostLutPoint {
        x: -161692,
        s: 22219176801783,
    },
    CostLutPoint {
        x: -160723,
        s: 22546808569489,
    },
    CostLutPoint {
        x: -159758,
        s: 22877550853313,
    },
    CostLutPoint {
        x: -158798,
        s: 23211053636391,
    },
    CostLutPoint {
        x: -157843,
        s: 23547301893046,
    },
    CostLutPoint {
        x: -156893,
        s: 23886279771851,
    },
    CostLutPoint {
        x: -155947,
        s: 24228334564194,
    },
    CostLutPoint {
        x: -155006,
        s: 24573094402371,
    },
    CostLutPoint {
        x: -154070,
        s: 24920541030854,
    },
    CostLutPoint {
        x: -153139,
        s: 25270655353680,
    },
    CostLutPoint {
        x: -152212,
        s: 25623800844571,
    },
    CostLutPoint {
        x: -151289,
        s: 25979971542593,
    },
    CostLutPoint {
        x: -150372,
        s: 26338374159716,
    },
    CostLutPoint {
        x: -149459,
        s: 26699768058568,
    },
    CostLutPoint {
        x: -148550,
        s: 27064145102474,
    },
    CostLutPoint {
        x: -147646,
        s: 27431088039402,
    },
    CostLutPoint {
        x: -146746,
        s: 27800985642348,
    },
    CostLutPoint {
        x: -145851,
        s: 28173408983745,
    },
    CostLutPoint {
        x: -144960,
        s: 28548755503884,
    },
    CostLutPoint {
        x: -144074,
        s: 28926584466971,
    },
    CostLutPoint {
        x: -143192,
        s: 29307302096444,
    },
    CostLutPoint {
        x: -142315,
        s: 29690455721084,
    },
    CostLutPoint {
        x: -141442,
        s: 30076460462400,
    },
    CostLutPoint {
        x: -140573,
        s: 30465301709650,
    },
    CostLutPoint {
        x: -139709,
        s: 30856508701477,
    },
    CostLutPoint {
        x: -138849,
        s: 31250510167010,
    },
    CostLutPoint {
        x: -137993,
        s: 31647289337573,
    },
    CostLutPoint {
        x: -137141,
        s: 32046828753560,
    },
    CostLutPoint {
        x: -136294,
        s: 32448633143036,
    },
    CostLutPoint {
        x: -135451,
        s: 32853149808702,
    },
    CostLutPoint {
        x: -134612,
        s: 33260359125429,
    },
    CostLutPoint {
        x: -133777,
        s: 33670240775043,
    },
    CostLutPoint {
        x: -132947,
        s: 34082274531704,
    },
    CostLutPoint {
        x: -132120,
        s: 34497431524703,
    },
    CostLutPoint {
        x: -131298,
        s: 34914685286107,
    },
    CostLutPoint {
        x: -130479,
        s: 35335027924028,
    },
    CostLutPoint {
        x: -129665,
        s: 35757409117480,
    },
    CostLutPoint {
        x: -128855,
        s: 36182314739672,
    },
    CostLutPoint {
        x: -128049,
        s: 36609719552672,
    },
    CostLutPoint {
        x: -127247,
        s: 37039597631924,
    },
    CostLutPoint {
        x: -126449,
        s: 37471922367954,
    },
    CostLutPoint {
        x: -125655,
        s: 37906666468326,
    },
    CostLutPoint {
        x: -124864,
        s: 38344358209346,
    },
    CostLutPoint {
        x: -124078,
        s: 38783862273681,
    },
    CostLutPoint {
        x: -123296,
        s: 39225699772353,
    },
    CostLutPoint {
        x: -122517,
        s: 39670414526480,
    },
    CostLutPoint {
        x: -121743,
        s: 40116834120437,
    },
    CostLutPoint {
        x: -120972,
        s: 40566080806340,
    },
    CostLutPoint {
        x: -120205,
        s: 41017548823647,
    },
    CostLutPoint {
        x: -119442,
        s: 41471205572544,
    },
    CostLutPoint {
        x: -118683,
        s: 41927017796643,
    },
    CostLutPoint {
        x: -117927,
        s: 42385561130653,
    },
    CostLutPoint {
        x: -117176,
        s: 42845587950017,
    },
    CostLutPoint {
        x: -116428,
        s: 43308288202641,
    },
    CostLutPoint {
        x: -115683,
        s: 43773644230744,
    },
    CostLutPoint {
        x: -114943,
        s: 44240370341947,
    },
    CostLutPoint {
        x: -114206,
        s: 44709690945439,
    },
    CostLutPoint {
        x: -113473,
        s: 45180940737468,
    },
    CostLutPoint {
        x: -112743,
        s: 45654733566753,
    },
    CostLutPoint {
        x: -112017,
        s: 46130390762024,
    },
    CostLutPoint {
        x: -111295,
        s: 46607872890271,
    },
    CostLutPoint {
        x: -110576,
        s: 47087810514298,
    },
    CostLutPoint {
        x: -109861,
        s: 47569504787244,
    },
    CostLutPoint {
        x: -109149,
        s: 48053597534006,
    },
    CostLutPoint {
        x: -108441,
        s: 48539376414691,
    },
    CostLutPoint {
        x: -107737,
        s: 49026799108465,
    },
    CostLutPoint {
        x: -107036,
        s: 49516524459317,
    },
    CostLutPoint {
        x: -106338,
        s: 50008527807535,
    },
    CostLutPoint {
        x: -105644,
        s: 50502069708940,
    },
    CostLutPoint {
        x: -104953,
        s: 50997826243289,
    },
    CostLutPoint {
        x: -104266,
        s: 51495044357105,
    },
    CostLutPoint {
        x: -103582,
        s: 51994411700239,
    },
    CostLutPoint {
        x: -102902,
        s: 52495161582520,
    },
    CostLutPoint {
        x: -102225,
        s: 52997993293229,
    },
    CostLutPoint {
        x: -101551,
        s: 53502878751015,
    },
    CostLutPoint {
        x: -100881,
        s: 54009030781074,
    },
    CostLutPoint {
        x: -100214,
        s: 54517166277005,
    },
    CostLutPoint {
        x: -99551,
        s: 55026484371994,
    },
    CostLutPoint {
        x: -98890,
        s: 55538491560574,
    },
    CostLutPoint {
        x: -98233,
        s: 56051608282877,
    },
    CostLutPoint {
        x: -97579,
        s: 56566575135577,
    },
    CostLutPoint {
        x: -96929,
        s: 57082563843148,
    },
    CostLutPoint {
        x: -96282,
        s: 57600326935109,
    },
    CostLutPoint {
        x: -95638,
        s: 58119832316195,
    },
    CostLutPoint {
        x: -94997,
        s: 58641047481685,
    },
    CostLutPoint {
        x: -94359,
        s: 59163939522056,
    },
    CostLutPoint {
        x: -93725,
        s: 59687645857111,
    },
    CostLutPoint {
        x: -93093,
        s: 60213784851273,
    },
    CostLutPoint {
        x: -92465,
        s: 60740657392046,
    },
    CostLutPoint {
        x: -91840,
        s: 61269058250014,
    },
    CostLutPoint {
        x: -91218,
        s: 61798952547197,
    },
    CostLutPoint {
        x: -90599,
        s: 62330305032967,
    },
    CostLutPoint {
        x: -89983,
        s: 62863080089409,
    },
    CostLutPoint {
        x: -89371,
        s: 63396367101266,
    },
    CostLutPoint {
        x: -88761,
        s: 63931872502471,
    },
    CostLutPoint {
        x: -88154,
        s: 64468691468282,
    },
    CostLutPoint {
        x: -87551,
        s: 65005892829631,
    },
    CostLutPoint {
        x: -86950,
        s: 65545220981908,
    },
    CostLutPoint {
        x: -86353,
        s: 66084843442531,
    },
    CostLutPoint {
        x: -85758,
        s: 66626529965694,
    },
    CostLutPoint {
        x: -85166,
        s: 67169341562965,
    },
    CostLutPoint {
        x: -84577,
        s: 67713239567741,
    },
    CostLutPoint {
        x: -83992,
        s: 68257251808714,
    },
    CostLutPoint {
        x: -83409,
        s: 68803198884287,
    },
    CostLutPoint {
        x: -82829,
        s: 69350114538950,
    },
    CostLutPoint {
        x: -82252,
        s: 69897958907754,
    },
    CostLutPoint {
        x: -81677,
        s: 70447651085597,
    },
    CostLutPoint {
        x: -81106,
        s: 70997238665579,
    },
    CostLutPoint {
        x: -80537,
        s: 71548605949870,
    },
    CostLutPoint {
        x: -79972,
        s: 72099773945643,
    },
    CostLutPoint {
        x: -79409,
        s: 72652652467228,
    },
    CostLutPoint {
        x: -78849,
        s: 73206227764599,
    },
    CostLutPoint {
        x: -78291,
        s: 73761456391428,
    },
    CostLutPoint {
        x: -77737,
        s: 74316306299746,
    },
    CostLutPoint {
        x: -77185,
        s: 74872738347004,
    },
    CostLutPoint {
        x: -76636,
        s: 75429711799209,
    },
    CostLutPoint {
        x: -76090,
        s: 75987183985838,
    },
    CostLutPoint {
        x: -75546,
        s: 76546142760458,
    },
    CostLutPoint {
        x: -75005,
        s: 77105527241664,
    },
    CostLutPoint {
        x: -74467,
        s: 77665294111261,
    },
    CostLutPoint {
        x: -73931,
        s: 78226450022125,
    },
    CostLutPoint {
        x: -73399,
        s: 78786857392805,
    },
    CostLutPoint {
        x: -72868,
        s: 79349642207609,
    },
    CostLutPoint {
        x: -72341,
        s: 79911590479187,
    },
    CostLutPoint {
        x: -71816,
        s: 80474790562726,
    },
    CostLutPoint {
        x: -71294,
        s: 81038134914864,
    },
    CostLutPoint {
        x: -70774,
        s: 81602667778156,
    },
    CostLutPoint {
        x: -70257,
        s: 82167268373027,
    },
    CostLutPoint {
        x: -69742,
        s: 82732993460086,
    },
    CostLutPoint {
        x: -69230,
        s: 83298709065821,
    },
    CostLutPoint {
        x: -68721,
        s: 83864369938559,
    },
    CostLutPoint {
        x: -68214,
        s: 84431051610544,
    },
    CostLutPoint {
        x: -67709,
        s: 84998727733196,
    },
    CostLutPoint {
        x: -67207,
        s: 85566238098880,
    },
    CostLutPoint {
        x: -66708,
        s: 86133536904899,
    },
    CostLutPoint {
        x: -66211,
        s: 86701724659389,
    },
    CostLutPoint {
        x: -65717,
        s: 87269621633299,
    },
    CostLutPoint {
        x: -65225,
        s: 87838340793603,
    },
    CostLutPoint {
        x: -64735,
        s: 88407854902757,
    },
    CostLutPoint {
        x: -64248,
        s: 88976964811605,
    },
    CostLutPoint {
        x: -63763,
        s: 89546802133686,
    },
    CostLutPoint {
        x: -63281,
        s: 90116154851047,
    },
    CostLutPoint {
        x: -62801,
        s: 90686166992707,
    },
    CostLutPoint {
        x: -62324,
        s: 91255613737451,
    },
    CostLutPoint {
        x: -61849,
        s: 91825651502453,
    },
    CostLutPoint {
        x: -61376,
        s: 92396252201467,
    },
    CostLutPoint {
        x: -60905,
        s: 92967387635150,
    },
    CostLutPoint {
        x: -60437,
        s: 93537807523137,
    },
    CostLutPoint {
        x: -59972,
        s: 94107464770464,
    },
    CostLutPoint {
        x: -59508,
        s: 94678781030928,
    },
    CostLutPoint {
        x: -59047,
        s: 95249265152770,
    },
    CostLutPoint {
        x: -58588,
        s: 95820116654913,
    },
    CostLutPoint {
        x: -58132,
        s: 96390053827451,
    },
    CostLutPoint {
        x: -57678,
        s: 96960288452417,
    },
    CostLutPoint {
        x: -57226,
        s: 97530791628788,
    },
    CostLutPoint {
        x: -56776,
        s: 98101534375016,
    },
    CostLutPoint {
        x: -56328,
        s: 98672487632224,
    },
    CostLutPoint {
        x: -55883,
        s: 99242338643706,
    },
    CostLutPoint {
        x: -55440,
        s: 99812329631647,
    },
    CostLutPoint {
        x: -54999,
        s: 100382431357626,
    },
    CostLutPoint {
        x: -54560,
        s: 100952614519805,
    },
    CostLutPoint {
        x: -54124,
        s: 101521541846820,
    },
    CostLutPoint {
        x: -53690,
        s: 102090479751669,
    },
    CostLutPoint {
        x: -53257,
        s: 102660718758359,
    },
    CostLutPoint {
        x: -52827,
        s: 103229595467525,
    },
    CostLutPoint {
        x: -52400,
        s: 103797062327246,
    },
    CostLutPoint {
        x: -51974,
        s: 104365747701693,
    },
    CostLutPoint {
        x: -51550,
        s: 104934296008252,
    },
    CostLutPoint {
        x: -51129,
        s: 105501327747290,
    },
    CostLutPoint {
        x: -50709,
        s: 106069506985443,
    },
    CostLutPoint {
        x: -50292,
        s: 106636098415325,
    },
    CostLutPoint {
        x: -49877,
        s: 107202422180992,
    },
    CostLutPoint {
        x: -49464,
        s: 107768448556188,
    },
    CostLutPoint {
        x: -49052,
        s: 108335527132066,
    },
    CostLutPoint {
        x: -48643,
        s: 108900875317440,
    },
    CostLutPoint {
        x: -48236,
        s: 109465836804910,
    },
    CostLutPoint {
        x: -47831,
        s: 110030381802666,
    },
    CostLutPoint {
        x: -47428,
        s: 110594480510031,
    },
    CostLutPoint {
        x: -47027,
        s: 111158103120420,
    },
    CostLutPoint {
        x: -46628,
        s: 111721219824271,
    },
    CostLutPoint {
        x: -46231,
        s: 112283800811964,
    },
    CostLutPoint {
        x: -45836,
        s: 112845816276727,
    },
    CostLutPoint {
        x: -45443,
        s: 113407236417515,
    },
    CostLutPoint {
        x: -45052,
        s: 113968031441877,
    },
    CostLutPoint {
        x: -44663,
        s: 114528171568806,
    },
    CostLutPoint {
        x: -44276,
        s: 115087627031562,
    },
    CostLutPoint {
        x: -43890,
        s: 115647822186599,
    },
    CostLutPoint {
        x: -43507,
        s: 116205824718076,
    },
    CostLutPoint {
        x: -43125,
        s: 116764518734133,
    },
    CostLutPoint {
        x: -42746,
        s: 117320949432328,
    },
    CostLutPoint {
        x: -42368,
        s: 117878023431506,
    },
    CostLutPoint {
        x: -41992,
        s: 118434245695575,
    },
    CostLutPoint {
        x: -41618,
        s: 118989586575343,
    },
    CostLutPoint {
        x: -41246,
        s: 119544016456901,
    },
    CostLutPoint {
        x: -40876,
        s: 120097505764280,
    },
    CostLutPoint {
        x: -40508,
        s: 120650024962079,
    },
    CostLutPoint {
        x: -40141,
        s: 121203054181910,
    },
    CostLutPoint {
        x: -39776,
        s: 121755065252624,
    },
    CostLutPoint {
        x: -39413,
        s: 122306028712946,
    },
    CostLutPoint {
        x: -39052,
        s: 122855915151630,
    },
    CostLutPoint {
        x: -38693,
        s: 123404695209981,
    },
    CostLutPoint {
        x: -38335,
        s: 123953876296325,
    },
    CostLutPoint {
        x: -37980,
        s: 124500361090569,
    },
    CostLutPoint {
        x: -37626,
        s: 125047199151502,
    },
    CostLutPoint {
        x: -37273,
        s: 125594377317712,
    },
    CostLutPoint {
        x: -36923,
        s: 126138766279632,
    },
    CostLutPoint {
        x: -36574,
        s: 126683447727673,
    },
    CostLutPoint {
        x: -36227,
        s: 127226839861688,
    },
    CostLutPoint {
        x: -35882,
        s: 127768913692800,
    },
    CostLutPoint {
        x: -35538,
        s: 128311219386683,
    },
    CostLutPoint {
        x: -35196,
        s: 128852159433830,
    },
    CostLutPoint {
        x: -34856,
        s: 129391705000086,
    },
    CostLutPoint {
        x: -34518,
        s: 129929827330125,
    },
    CostLutPoint {
        x: -34181,
        s: 130468097563097,
    },
    CostLutPoint {
        x: -33846,
        s: 131004897549259,
    },
    CostLutPoint {
        x: -33513,
        s: 131540198710786,
    },
    CostLutPoint {
        x: -33181,
        s: 132075587718155,
    },
    CostLutPoint {
        x: -32851,
        s: 132609431148117,
    },
    CostLutPoint {
        x: -32522,
        s: 133143325923908,
    },
    CostLutPoint {
        x: -32195,
        s: 133675628518558,
    },
    CostLutPoint {
        x: -31870,
        s: 134206310660518,
    },
    CostLutPoint {
        x: -31547,
        s: 134735344174354,
    },
    CostLutPoint {
        x: -31225,
        s: 135264346331533,
    },
    CostLutPoint {
        x: -30904,
        s: 135793304032088,
    },
    CostLutPoint {
        x: -30585,
        s: 136320548884161,
    },
    CostLutPoint {
        x: -30268,
        s: 136846052963180,
    },
    CostLutPoint {
        x: -29953,
        s: 137369788449401,
    },
    CostLutPoint {
        x: -29639,
        s: 137893397611396,
    },
    CostLutPoint {
        x: -29326,
        s: 138416867429738,
    },
    CostLutPoint {
        x: -29015,
        s: 138938505160112,
    },
    CostLutPoint {
        x: -28706,
        s: 139458283263378,
    },
    CostLutPoint {
        x: -28398,
        s: 139977863662491,
    },
    CostLutPoint {
        x: -28092,
        s: 140495539256987,
    },
    CostLutPoint {
        x: -27787,
        s: 141012981685942,
    },
    CostLutPoint {
        x: -27483,
        s: 141530178042936,
    },
    CostLutPoint {
        x: -27182,
        s: 142043698575243,
    },
    CostLutPoint {
        x: -26881,
        s: 142558641459574,
    },
    CostLutPoint {
        x: -26583,
        s: 143069854486051,
    },
    CostLutPoint {
        x: -26285,
        s: 143582464233112,
    },
    CostLutPoint {
        x: -25990,
        s: 144091290420464,
    },
    CostLutPoint {
        x: -25695,
        s: 144601487801307,
    },
    CostLutPoint {
        x: -25402,
        s: 145109584684582,
    },
    CostLutPoint {
        x: -25111,
        s: 145615554500185,
    },
    CostLutPoint {
        x: -24821,
        s: 146121116409227,
    },
    CostLutPoint {
        x: -24532,
        s: 146626257769467,
    },
    CostLutPoint {
        x: -24245,
        s: 147129211221004,
    },
    CostLutPoint {
        x: -23960,
        s: 147629950555793,
    },
    CostLutPoint {
        x: -23675,
        s: 148131977182672,
    },
    CostLutPoint {
        x: -23393,
        s: 148629987343789,
    },
    CostLutPoint {
        x: -23111,
        s: 149129259788799,
    },
    CostLutPoint {
        x: -22831,
        s: 149626241123164,
    },
    CostLutPoint {
        x: -22553,
        s: 150120905573729,
    },
    CostLutPoint {
        x: -22275,
        s: 150616799483701,
    },
    CostLutPoint {
        x: -21999,
        s: 151110342907237,
    },
    CostLutPoint {
        x: -21725,
        s: 151601510326779,
    },
    CostLutPoint {
        x: -21452,
        s: 152092075480577,
    },
    CostLutPoint {
        x: -21180,
        s: 152582026115909,
    },
    CostLutPoint {
        x: -20910,
        s: 153069542221670,
    },
    CostLutPoint {
        x: -20641,
        s: 153556410753710,
    },
    CostLutPoint {
        x: -20373,
        s: 154042619562919,
    },
    CostLutPoint {
        x: -20106,
        s: 154528156522696,
    },
    CostLutPoint {
        x: -19841,
        s: 155011184652294,
    },
    CostLutPoint {
        x: -19578,
        s: 155491679184405,
    },
    CostLutPoint {
        x: -19315,
        s: 155973282067949,
    },
    CostLutPoint {
        x: -19054,
        s: 156452318959059,
    },
    CostLutPoint {
        x: -18794,
        s: 156930607022527,
    },
    CostLutPoint {
        x: -18536,
        s: 157406288552355,
    },
    CostLutPoint {
        x: -18278,
        s: 157883039142849,
    },
    CostLutPoint {
        x: -18022,
        s: 158357151233227,
    },
    CostLutPoint {
        x: -17768,
        s: 158828600700421,
    },
    CostLutPoint {
        x: -17514,
        s: 159301088008389,
    },
    CostLutPoint {
        x: -17262,
        s: 159770881089382,
    },
    CostLutPoint {
        x: -17011,
        s: 160239826442005,
    },
    CostLutPoint {
        x: -16762,
        s: 160706038092410,
    },
    CostLutPoint {
        x: -16513,
        s: 161173249133001,
    },
    CostLutPoint {
        x: -16266,
        s: 161637695328560,
    },
    CostLutPoint {
        x: -16020,
        s: 162101239538312,
    },
    CostLutPoint {
        x: -15775,
        s: 162563870301699,
    },
    CostLutPoint {
        x: -15532,
        s: 163023681989311,
    },
    CostLutPoint {
        x: -15289,
        s: 163484447676145,
    },
    CostLutPoint {
        x: -15048,
        s: 163942363714435,
    },
    CostLutPoint {
        x: -14808,
        s: 164399313013565,
    },
    CostLutPoint {
        x: -14570,
        s: 164853374560412,
    },
    CostLutPoint {
        x: -14332,
        s: 165308352788265,
    },
    CostLutPoint {
        x: -14096,
        s: 165760413188263,
    },
    CostLutPoint {
        x: -13861,
        s: 166211454402006,
    },
    CostLutPoint {
        x: -13627,
        s: 166661465350010,
    },
    CostLutPoint {
        x: -13394,
        s: 167110434987290,
    },
    CostLutPoint {
        x: -13162,
        s: 167558352303674,
    },
    CostLutPoint {
        x: -12932,
        s: 168003270025406,
    },
    CostLutPoint {
        x: -12702,
        s: 168449046077781,
    },
    CostLutPoint {
        x: -12474,
        s: 168891793273162,
    },
    CostLutPoint {
        x: -12247,
        s: 169333437087467,
    },
    CostLutPoint {
        x: -12021,
        s: 169773966734387,
    },
    CostLutPoint {
        x: -11796,
        s: 170213371464380,
    },
    CostLutPoint {
        x: -11572,
        s: 170651640564961,
    },
    CostLutPoint {
        x: -11350,
        s: 171086801364190,
    },
    CostLutPoint {
        x: -11128,
        s: 171522763607468,
    },
    CostLutPoint {
        x: -10908,
        s: 171955589137664,
    },
    CostLutPoint {
        x: -10689,
        s: 172387229435881,
    },
    CostLutPoint {
        x: -10470,
        s: 172819650323931,
    },
    CostLutPoint {
        x: -10253,
        s: 173248892298775,
    },
    CostLutPoint {
        x: -10037,
        s: 173676917711514,
    },
    CostLutPoint {
        x: -9822,
        s: 174103716202146,
    },
    CostLutPoint {
        x: -9608,
        s: 174529277450225,
    },
    CostLutPoint {
        x: -9395,
        s: 174953591175098,
    },
    CostLutPoint {
        x: -9184,
        s: 175374649869237,
    },
    CostLutPoint {
        x: -8973,
        s: 175796434425619,
    },
    CostLutPoint {
        x: -8763,
        s: 176216940873528,
    },
    CostLutPoint {
        x: -8555,
        s: 176634151568479,
    },
    CostLutPoint {
        x: -8347,
        s: 177052068089349,
    },
    CostLutPoint {
        x: -8140,
        s: 177468676283148,
    },
    CostLutPoint {
        x: -7935,
        s: 177881948510942,
    },
    CostLutPoint {
        x: -7730,
        s: 178295906758721,
    },
    CostLutPoint {
        x: -7527,
        s: 178706502528588,
    },
    CostLutPoint {
        x: -7324,
        s: 179117771244763,
    },
    CostLutPoint {
        x: -7123,
        s: 179525651202214,
    },
    CostLutPoint {
        x: -6922,
        s: 179934191138364,
    },
    CostLutPoint {
        x: -6723,
        s: 180339316267861,
    },
    CostLutPoint {
        x: -6524,
        s: 180745088515889,
    },
    CostLutPoint {
        x: -6327,
        s: 181147420143938,
    },
    CostLutPoint {
        x: -6130,
        s: 181550386139113,
    },
    CostLutPoint {
        x: -5935,
        s: 181949885937246,
    },
    CostLutPoint {
        x: -5740,
        s: 182350007461143,
    },
    CostLutPoint {
        x: -5547,
        s: 182746637448799,
    },
    CostLutPoint {
        x: -5354,
        s: 183143876632127,
    },
    CostLutPoint {
        x: -5162,
        s: 183539662124377,
    },
    CostLutPoint {
        x: -4972,
        s: 183931918504753,
    },
    CostLutPoint {
        x: -4782,
        s: 184324765497061,
    },
    CostLutPoint {
        x: -4593,
        s: 184716130894081,
    },
    CostLutPoint {
        x: -4405,
        s: 185106005478233,
    },
    CostLutPoint {
        x: -4218,
        s: 185494380076765,
    },
    CostLutPoint {
        x: -4032,
        s: 185881245561905,
    },
    CostLutPoint {
        x: -3847,
        s: 186266592851006,
    },
    CostLutPoint {
        x: -3663,
        s: 186650412906694,
    },
    CostLutPoint {
        x: -3480,
        s: 187032696737001,
    },
    CostLutPoint {
        x: -3297,
        s: 187415528864310,
    },
    CostLutPoint {
        x: -3116,
        s: 187794716414007,
    },
    CostLutPoint {
        x: -2935,
        s: 188174440416517,
    },
    CostLutPoint {
        x: -2756,
        s: 188550496201285,
    },
    CostLutPoint {
        x: -2577,
        s: 188927076713608,
    },
    CostLutPoint {
        x: -2399,
        s: 189302073791630,
    },
    CostLutPoint {
        x: -2222,
        s: 189675478716210,
    },
    CostLutPoint {
        x: -2046,
        s: 190047282814588,
    },
    CostLutPoint {
        x: -1871,
        s: 190417477460500,
    },
    CostLutPoint {
        x: -1696,
        s: 190788173764035,
    },
    CostLutPoint {
        x: -1523,
        s: 191155126646780,
    },
    CostLutPoint {
        x: -1350,
        s: 191522569819920,
    },
    CostLutPoint {
        x: -1179,
        s: 191886246930007,
    },
    CostLutPoint {
        x: -1008,
        s: 192250403085741,
    },
    CostLutPoint {
        x: -838,
        s: 192612904535315,
    },
    CostLutPoint {
        x: -668,
        s: 192975879463002,
    },
    CostLutPoint {
        x: -500,
        s: 193335049259715,
    },
    CostLutPoint {
        x: -333,
        s: 193692539435609,
    },
    CostLutPoint {
        x: -166,
        s: 194050486541806,
    },
    CostLutPoint {
        x: 0,
        s: 194406743088682,
    },
    CostLutPoint {
        x: 166,
        s: 194763451112942,
    },
    CostLutPoint {
        x: 333,
        s: 195122763545177,
    },
    CostLutPoint {
        x: 500,
        s: 195482532907715,
    },
    CostLutPoint {
        x: 668,
        s: 195844917616730,
    },
    CostLutPoint {
        x: 838,
        s: 196212087129363,
    },
    CostLutPoint {
        x: 1008,
        s: 196579730120109,
    },
    CostLutPoint {
        x: 1179,
        s: 196950013371991,
    },
    CostLutPoint {
        x: 1350,
        s: 197320775669520,
    },
    CostLutPoint {
        x: 1523,
        s: 197696361838588,
    },
    CostLutPoint {
        x: 1696,
        s: 198072438298051,
    },
    CostLutPoint {
        x: 1871,
        s: 198453361271316,
    },
    CostLutPoint {
        x: 2046,
        s: 198834785902204,
    },
    CostLutPoint {
        x: 2222,
        s: 199218896047922,
    },
    CostLutPoint {
        x: 2399,
        s: 199605700334734,
    },
    CostLutPoint {
        x: 2577,
        s: 199995207435400,
    },
    CostLutPoint {
        x: 2756,
        s: 200387426069061,
    },
    CostLutPoint {
        x: 2935,
        s: 200780169430277,
    },
    CostLutPoint {
        x: 3116,
        s: 201177834508343,
    },
    CostLutPoint {
        x: 3297,
        s: 201576036039222,
    },
    CostLutPoint {
        x: 3480,
        s: 201979182927081,
    },
    CostLutPoint {
        x: 3663,
        s: 202382878111942,
    },
    CostLutPoint {
        x: 3847,
        s: 202789332038718,
    },
    CostLutPoint {
        x: 4032,
        s: 203198553699377,
    },
    CostLutPoint {
        x: 4218,
        s: 203610552131293,
    },
    CostLutPoint {
        x: 4405,
        s: 204025336417113,
    },
    CostLutPoint {
        x: 4593,
        s: 204442915684609,
    },
    CostLutPoint {
        x: 4782,
        s: 204863299106533,
    },
    CostLutPoint {
        x: 4972,
        s: 205286495900465,
    },
    CostLutPoint {
        x: 5162,
        s: 205710283306329,
    },
    CostLutPoint {
        x: 5354,
        s: 206139131534911,
    },
    CostLutPoint {
        x: 5547,
        s: 206570821039711,
    },
    CostLutPoint {
        x: 5740,
        s: 207003119740183,
    },
    CostLutPoint {
        x: 5935,
        s: 207440516839006,
    },
    CostLutPoint {
        x: 6130,
        s: 207878535663593,
    },
    CostLutPoint {
        x: 6327,
        s: 208321678225730,
    },
    CostLutPoint {
        x: 6524,
        s: 208765455154993,
    },
    CostLutPoint {
        x: 6723,
        s: 209214381398869,
    },
    CostLutPoint {
        x: 6922,
        s: 209663954761276,
    },
    CostLutPoint {
        x: 7123,
        s: 210118703251622,
    },
    CostLutPoint {
        x: 7324,
        s: 210574111720667,
    },
    CostLutPoint {
        x: 7527,
        s: 211034721365580,
    },
    CostLutPoint {
        x: 7730,
        s: 211496003956801,
    },
    CostLutPoint {
        x: 7935,
        s: 211962514004702,
    },
    CostLutPoint {
        x: 8140,
        s: 212429710072588,
    },
    CostLutPoint {
        x: 8347,
        s: 212902160109061,
    },
    CostLutPoint {
        x: 8555,
        s: 213377596785759,
    },
    CostLutPoint {
        x: 8763,
        s: 213853739288376,
    },
    CostLutPoint {
        x: 8973,
        s: 214335175972627,
    },
    CostLutPoint {
        x: 9184,
        s: 214819629515701,
    },
    CostLutPoint {
        x: 9395,
        s: 215304808921018,
    },
    CostLutPoint {
        x: 9608,
        s: 215795323230193,
    },
    CostLutPoint {
        x: 9822,
        s: 216288884983458,
    },
    CostLutPoint {
        x: 10037,
        s: 216785504461466,
    },
    CostLutPoint {
        x: 10253,
        s: 217285191984663,
    },
    CostLutPoint {
        x: 10470,
        s: 217787957913051,
    },
    CostLutPoint {
        x: 10689,
        s: 218296134862825,
    },
    CostLutPoint {
        x: 10908,
        s: 218805092402432,
    },
    CostLutPoint {
        x: 11128,
        s: 219317159677356,
    },
    CostLutPoint {
        x: 11350,
        s: 219834680173790,
    },
    CostLutPoint {
        x: 11572,
        s: 220353002114273,
    },
    CostLutPoint {
        x: 11796,
        s: 220876805687996,
    },
    CostLutPoint {
        x: 12021,
        s: 221403768599603,
    },
    CostLutPoint {
        x: 12247,
        s: 221933901561579,
    },
    CostLutPoint {
        x: 12474,
        s: 222467215323466,
    },
    CostLutPoint {
        x: 12702,
        s: 223003720671573,
    },
    CostLutPoint {
        x: 12932,
        s: 223545787097278,
    },
    CostLutPoint {
        x: 13162,
        s: 224088711853626,
    },
    CostLutPoint {
        x: 13394,
        s: 224637226949914,
    },
    CostLutPoint {
        x: 13627,
        s: 225188984692602,
    },
    CostLutPoint {
        x: 13861,
        s: 225743996091862,
    },
    CostLutPoint {
        x: 14096,
        s: 226302272192679,
    },
    CostLutPoint {
        x: 14332,
        s: 226863824074537,
    },
    CostLutPoint {
        x: 14570,
        s: 227431048063132,
    },
    CostLutPoint {
        x: 14808,
        s: 227999188732733,
    },
    CostLutPoint {
        x: 15048,
        s: 228573031584643,
    },
    CostLutPoint {
        x: 15289,
        s: 229150202664689,
    },
    CostLutPoint {
        x: 15532,
        s: 229733114030783,
    },
    CostLutPoint {
        x: 15775,
        s: 230316979396099,
    },
    CostLutPoint {
        x: 16020,
        s: 230906615620232,
    },
    CostLutPoint {
        x: 16266,
        s: 231499633365296,
    },
    CostLutPoint {
        x: 16513,
        s: 232096044091849,
    },
    CostLutPoint {
        x: 16762,
        s: 232698279907962,
    },
    CostLutPoint {
        x: 17011,
        s: 233301515114261,
    },
    CostLutPoint {
        x: 17262,
        s: 233910606552934,
    },
    CostLutPoint {
        x: 17514,
        s: 234523145230533,
    },
    CostLutPoint {
        x: 17768,
        s: 235141579615749,
    },
    CostLutPoint {
        x: 18022,
        s: 235761051841739,
    },
    CostLutPoint {
        x: 18278,
        s: 236386451379137,
    },
    CostLutPoint {
        x: 18536,
        s: 237017802351011,
    },
    CostLutPoint {
        x: 18794,
        s: 237650222383551,
    },
    CostLutPoint {
        x: 19054,
        s: 238288625817043,
    },
    CostLutPoint {
        x: 19315,
        s: 238930575390189,
    },
    CostLutPoint {
        x: 19578,
        s: 239578548905493,
    },
    CostLutPoint {
        x: 19841,
        s: 240227630772230,
    },
    CostLutPoint {
        x: 20106,
        s: 240882768976072,
    },
    CostLutPoint {
        x: 20373,
        s: 241543988284327,
    },
    CostLutPoint {
        x: 20641,
        s: 242208830710446,
    },
    CostLutPoint {
        x: 20910,
        s: 242877308381030,
    },
    CostLutPoint {
        x: 21180,
        s: 243549433445189,
    },
    CostLutPoint {
        x: 21452,
        s: 244227713914369,
    },
    CostLutPoint {
        x: 21725,
        s: 244909674832379,
    },
    CostLutPoint {
        x: 21999,
        s: 245595328451941,
    },
    CostLutPoint {
        x: 22275,
        s: 246287196002101,
    },
    CostLutPoint {
        x: 22553,
        s: 246985303000417,
    },
    CostLutPoint {
        x: 22831,
        s: 247684639458140,
    },
    CostLutPoint {
        x: 23111,
        s: 248390248966655,
    },
    CostLutPoint {
        x: 23393,
        s: 249102157299117,
    },
    CostLutPoint {
        x: 23675,
        s: 249815327915472,
    },
    CostLutPoint {
        x: 23960,
        s: 250537366967953,
    },
    CostLutPoint {
        x: 24245,
        s: 251260693312524,
    },
    CostLutPoint {
        x: 24532,
        s: 251990395474939,
    },
    CostLutPoint {
        x: 24821,
        s: 252726499663243,
    },
    CostLutPoint {
        x: 25111,
        s: 253466478270041,
    },
    CostLutPoint {
        x: 25402,
        s: 254210343937574,
    },
    CostLutPoint {
        x: 25695,
        s: 254960672472027,
    },
    CostLutPoint {
        x: 25990,
        s: 255717490443504,
    },
    CostLutPoint {
        x: 26285,
        s: 256475679608472,
    },
    CostLutPoint {
        x: 26583,
        s: 257242970115619,
    },
    CostLutPoint {
        x: 26881,
        s: 258011657343350,
    },
    CostLutPoint {
        x: 27182,
        s: 258789499615115,
    },
    CostLutPoint {
        x: 27483,
        s: 259568764238904,
    },
    CostLutPoint {
        x: 27787,
        s: 260357237939894,
    },
    CostLutPoint {
        x: 28092,
        s: 261149760536219,
    },
    CostLutPoint {
        x: 28398,
        s: 261946344934299,
    },
    CostLutPoint {
        x: 28706,
        s: 262749614462354,
    },
    CostLutPoint {
        x: 29015,
        s: 263556981253552,
    },
    CostLutPoint {
        x: 29326,
        s: 264371078352234,
    },
    CostLutPoint {
        x: 29639,
        s: 265191933297540,
    },
    CostLutPoint {
        x: 29953,
        s: 266016943866489,
    },
    CostLutPoint {
        x: 30268,
        s: 266846123078508,
    },
    CostLutPoint {
        x: 30585,
        s: 267682123632321,
    },
    CostLutPoint {
        x: 30904,
        s: 268524973347672,
    },
    CostLutPoint {
        x: 31225,
        s: 269374700149133,
    },
    CostLutPoint {
        x: 31547,
        s: 270228677461266,
    },
    CostLutPoint {
        x: 31870,
        s: 271086918384038,
    },
    CostLutPoint {
        x: 32195,
        s: 271952100613278,
    },
    CostLutPoint {
        x: 32522,
        s: 272824252324420,
    },
    CostLutPoint {
        x: 32851,
        s: 273703401789013,
    },
    CostLutPoint {
        x: 33181,
        s: 274586897566731,
    },
    CostLutPoint {
        x: 33513,
        s: 275477437701634,
    },
    CostLutPoint {
        x: 33846,
        s: 276372360649675,
    },
    CostLutPoint {
        x: 34181,
        s: 277274374707673,
    },
    CostLutPoint {
        x: 34518,
        s: 278183508453453,
    },
    CostLutPoint {
        x: 34856,
        s: 279097085069462,
    },
    CostLutPoint {
        x: 35196,
        s: 280017828383846,
    },
    CostLutPoint {
        x: 35538,
        s: 280945767151931,
    },
    CostLutPoint {
        x: 35882,
        s: 281880930207872,
    },
    CostLutPoint {
        x: 36227,
        s: 282820620093880,
    },
    CostLutPoint {
        x: 36574,
        s: 283767581611577,
    },
    CostLutPoint {
        x: 36923,
        s: 284721843749840,
    },
    CostLutPoint {
        x: 37273,
        s: 285680693341520,
    },
    CostLutPoint {
        x: 37626,
        s: 286649638630798,
    },
    CostLutPoint {
        x: 37980,
        s: 287623218992649,
    },
    CostLutPoint {
        x: 38335,
        s: 288601447588485,
    },
    CostLutPoint {
        x: 38693,
        s: 289589864794109,
    },
    CostLutPoint {
        x: 39052,
        s: 290582977995022,
    },
    CostLutPoint {
        x: 39413,
        s: 291583574750194,
    },
    CostLutPoint {
        x: 39776,
        s: 292591684418320,
    },
    CostLutPoint {
        x: 40141,
        s: 293607336410646,
    },
    CostLutPoint {
        x: 40508,
        s: 294630560188447,
    },
    CostLutPoint {
        x: 40876,
        s: 295658588955576,
    },
    CostLutPoint {
        x: 41246,
        s: 296694237547717,
    },
    CostLutPoint {
        x: 41618,
        s: 297737535500271,
    },
    CostLutPoint {
        x: 41992,
        s: 298788512389207,
    },
    CostLutPoint {
        x: 42368,
        s: 299847197828434,
    },
    CostLutPoint {
        x: 42746,
        s: 300913621467144,
    },
    CostLutPoint {
        x: 43125,
        s: 301984983374133,
    },
    CostLutPoint {
        x: 43507,
        s: 303066966865148,
    },
    CostLutPoint {
        x: 43890,
        s: 304153936808039,
    },
    CostLutPoint {
        x: 44276,
        s: 305251599029258,
    },
    CostLutPoint {
        x: 44663,
        s: 306354295910054,
    },
    CostLutPoint {
        x: 45052,
        s: 307464898061269,
    },
    CostLutPoint {
        x: 45443,
        s: 308583435249643,
    },
    CostLutPoint {
        x: 45836,
        s: 309709937256183,
    },
    CostLutPoint {
        x: 46231,
        s: 310844433873340,
    },
    CostLutPoint {
        x: 46628,
        s: 311986954902159,
    },
    CostLutPoint {
        x: 47027,
        s: 313137530149412,
    },
    CostLutPoint {
        x: 47428,
        s: 314296189424719,
    },
    CostLutPoint {
        x: 47831,
        s: 315462962537642,
    },
    CostLutPoint {
        x: 48236,
        s: 316637879294766,
    },
    CostLutPoint {
        x: 48643,
        s: 317820969496768,
    },
    CostLutPoint {
        x: 49052,
        s: 319012262935458,
    },
    CostLutPoint {
        x: 49464,
        s: 320214710885532,
    },
    CostLutPoint {
        x: 49877,
        s: 321422506003584,
    },
    CostLutPoint {
        x: 50292,
        s: 322638593665757,
    },
    CostLutPoint {
        x: 50709,
        s: 323863003598307,
    },
    CostLutPoint {
        x: 51129,
        s: 325098710624474,
    },
    CostLutPoint {
        x: 51550,
        s: 326339860117052,
    },
    CostLutPoint {
        x: 51974,
        s: 327592377943997,
    },
    CostLutPoint {
        x: 52400,
        s: 328853348637646,
    },
    CostLutPoint {
        x: 52827,
        s: 330119832813317,
    },
    CostLutPoint {
        x: 53257,
        s: 331397792041431,
    },
    CostLutPoint {
        x: 53690,
        s: 332687273873909,
    },
    CostLutPoint {
        x: 54124,
        s: 333982351775524,
    },
    CostLutPoint {
        x: 54560,
        s: 335286030189565,
    },
    CostLutPoint {
        x: 54999,
        s: 336601337670330,
    },
    CostLutPoint {
        x: 55440,
        s: 337925316521888,
    },
    CostLutPoint {
        x: 55883,
        s: 339257996046074,
    },
    CostLutPoint {
        x: 56328,
        s: 340599405481312,
    },
    CostLutPoint {
        x: 56776,
        s: 341952597572712,
    },
    CostLutPoint {
        x: 57226,
        s: 343314590109684,
    },
    CostLutPoint {
        x: 57678,
        s: 344685412151105,
    },
    CostLutPoint {
        x: 58132,
        s: 346065092678523,
    },
    CostLutPoint {
        x: 58588,
        s: 347453660592961,
    },
    CostLutPoint {
        x: 59047,
        s: 348854199079682,
    },
    CostLutPoint {
        x: 59508,
        s: 350263694881296,
    },
    CostLutPoint {
        x: 59972,
        s: 351685243446176,
    },
    CostLutPoint {
        x: 60437,
        s: 353112745991489,
    },
    CostLutPoint {
        x: 60905,
        s: 354552370798030,
    },
    CostLutPoint {
        x: 61376,
        s: 356004164960763,
    },
    CostLutPoint {
        x: 61849,
        s: 357465083792757,
    },
    CostLutPoint {
        x: 62324,
        s: 358935155493355,
    },
    CostLutPoint {
        x: 62801,
        s: 360414408148803,
    },
    CostLutPoint {
        x: 63281,
        s: 361905980309223,
    },
    CostLutPoint {
        x: 63763,
        s: 363406801828534,
    },
    CostLutPoint {
        x: 64248,
        s: 364920023645013,
    },
    CostLutPoint {
        x: 64735,
        s: 366442562809317,
    },
    CostLutPoint {
        x: 65225,
        s: 367977582675203,
    },
    CostLutPoint {
        x: 65717,
        s: 369521987424531,
    },
    CostLutPoint {
        x: 66211,
        s: 371075804294845,
    },
    CostLutPoint {
        x: 66708,
        s: 372642215286467,
    },
    CostLutPoint {
        x: 67207,
        s: 374218105161152,
    },
    CostLutPoint {
        x: 67709,
        s: 375806668378060,
    },
    CostLutPoint {
        x: 68214,
        s: 377407950739888,
    },
    CostLutPoint {
        x: 68721,
        s: 379018817486975,
    },
    CostLutPoint {
        x: 69230,
        s: 380639294967901,
    },
    CostLutPoint {
        x: 69742,
        s: 382272602617718,
    },
    CostLutPoint {
        x: 70257,
        s: 383918785688099,
    },
    CostLutPoint {
        x: 70774,
        s: 385574683185261,
    },
    CostLutPoint {
        x: 71294,
        s: 387243533315888,
    },
    CostLutPoint {
        x: 71816,
        s: 388922161892262,
    },
    CostLutPoint {
        x: 72341,
        s: 390613819639123,
    },
    CostLutPoint {
        x: 72868,
        s: 392315319132537,
    },
    CostLutPoint {
        x: 73399,
        s: 394033161951909,
    },
    CostLutPoint {
        x: 73931,
        s: 395757677182701,
    },
    CostLutPoint {
        x: 74467,
        s: 397498623742493,
    },
    CostLutPoint {
        x: 75005,
        s: 399249549278144,
    },
    CostLutPoint {
        x: 75546,
        s: 401013742104074,
    },
    CostLutPoint {
        x: 76090,
        s: 402791245538478,
    },
    CostLutPoint {
        x: 76636,
        s: 404578825495465,
    },
    CostLutPoint {
        x: 77185,
        s: 406379789088764,
    },
    CostLutPoint {
        x: 77737,
        s: 408194178988898,
    },
    CostLutPoint {
        x: 78291,
        s: 410018740962564,
    },
    CostLutPoint {
        x: 78849,
        s: 411860104086903,
    },
    CostLutPoint {
        x: 79409,
        s: 413711710475293,
    },
    CostLutPoint {
        x: 79972,
        s: 415576898541355,
    },
    CostLutPoint {
        x: 80537,
        s: 417452387067822,
    },
    CostLutPoint {
        x: 81106,
        s: 419344856174955,
    },
    CostLutPoint {
        x: 81677,
        s: 421247694920989,
    },
    CostLutPoint {
        x: 82252,
        s: 423167608938346,
    },
    CostLutPoint {
        x: 82829,
        s: 425097960699334,
    },
    CostLutPoint {
        x: 83409,
        s: 427042126076351,
    },
    CostLutPoint {
        x: 83992,
        s: 429000144934346,
    },
    CostLutPoint {
        x: 84577,
        s: 430968688561533,
    },
    CostLutPoint {
        x: 85166,
        s: 432954526294101,
    },
    CostLutPoint {
        x: 85758,
        s: 434954335336062,
    },
    CostLutPoint {
        x: 86353,
        s: 436968154354019,
    },
    CostLutPoint {
        x: 86950,
        s: 438992627369108,
    },
    CostLutPoint {
        x: 87551,
        s: 441034574561727,
    },
    CostLutPoint {
        x: 88154,
        s: 443087238479866,
    },
    CostLutPoint {
        x: 88761,
        s: 445157464662728,
    },
    CostLutPoint {
        x: 89371,
        s: 447241889312082,
    },
    CostLutPoint {
        x: 89983,
        s: 449337122285377,
    },
    CostLutPoint {
        x: 90599,
        s: 451450047083271,
    },
    CostLutPoint {
        x: 91218,
        s: 453577279353725,
    },
    CostLutPoint {
        x: 91840,
        s: 455718854714654,
    },
    CostLutPoint {
        x: 92465,
        s: 457874808416686,
    },
    CostLutPoint {
        x: 93093,
        s: 460045175337801,
    },
    CostLutPoint {
        x: 93725,
        s: 462233455674711,
    },
    CostLutPoint {
        x: 94359,
        s: 464432758605320,
    },
    CostLutPoint {
        x: 94997,
        s: 466650055699797,
    },
    CostLutPoint {
        x: 95638,
        s: 468881914571043,
    },
    CostLutPoint {
        x: 96282,
        s: 471128368128581,
    },
    CostLutPoint {
        x: 96929,
        s: 473389448877132,
    },
    CostLutPoint {
        x: 97579,
        s: 475665188911961,
    },
    CostLutPoint {
        x: 98233,
        s: 477959130670845,
    },
    CostLutPoint {
        x: 98890,
        s: 480267807462014,
    },
    CostLutPoint {
        x: 99551,
        s: 482594773656090,
    },
    CostLutPoint {
        x: 100214,
        s: 484933018878349,
    },
    CostLutPoint {
        x: 100881,
        s: 487289626568850,
    },
    CostLutPoint {
        x: 101551,
        s: 489661102627111,
    },
    CostLutPoint {
        x: 102225,
        s: 492051025126829,
    },
    CostLutPoint {
        x: 102902,
        s: 494455886275512,
    },
    CostLutPoint {
        x: 103582,
        s: 496875714154511,
    },
    CostLutPoint {
        x: 104266,
        s: 499314104441841,
    },
    CostLutPoint {
        x: 104953,
        s: 501767528860377,
    },
    CostLutPoint {
        x: 105644,
        s: 504239594727564,
    },
    CostLutPoint {
        x: 106338,
        s: 506726760129583,
    },
    CostLutPoint {
        x: 107036,
        s: 509232643953973,
    },
    CostLutPoint {
        x: 107737,
        s: 511753690677617,
    },
    CostLutPoint {
        x: 108441,
        s: 514289924960227,
    },
    CostLutPoint {
        x: 109149,
        s: 516844982925110,
    },
    CostLutPoint {
        x: 109861,
        s: 519418906893100,
    },
    CostLutPoint {
        x: 110576,
        s: 522008114236794,
    },
    CostLutPoint {
        x: 111295,
        s: 524616258098591,
    },
    CostLutPoint {
        x: 112017,
        s: 527239742358056,
    },
    CostLutPoint {
        x: 112743,
        s: 529882231419681,
    },
    CostLutPoint {
        x: 113473,
        s: 532543764716476,
    },
    CostLutPoint {
        x: 114206,
        s: 535220725952415,
    },
    CostLutPoint {
        x: 114943,
        s: 537916796246075,
    },
    CostLutPoint {
        x: 115683,
        s: 540628345933912,
    },
    CostLutPoint {
        x: 116428,
        s: 543362740541329,
    },
    CostLutPoint {
        x: 117176,
        s: 546112675826113,
    },
    CostLutPoint {
        x: 117927,
        s: 548878169446045,
    },
    CostLutPoint {
        x: 118683,
        s: 551666621387811,
    },
    CostLutPoint {
        x: 119442,
        s: 554470689341376,
    },
    CostLutPoint {
        x: 120205,
        s: 557294092639327,
    },
    CostLutPoint {
        x: 120972,
        s: 560136864538052,
    },
    CostLutPoint {
        x: 121743,
        s: 562999037637365,
    },
    CostLutPoint {
        x: 122517,
        s: 565876922730512,
    },
    CostLutPoint {
        x: 123296,
        s: 568777987499969,
    },
    CostLutPoint {
        x: 124078,
        s: 571694814426769,
    },
    CostLutPoint {
        x: 124864,
        s: 574631154657090,
    },
    CostLutPoint {
        x: 125655,
        s: 577590782047206,
    },
    CostLutPoint {
        x: 126449,
        s: 580566241979858,
    },
    CostLutPoint {
        x: 127247,
        s: 583561301146036,
    },
    CostLutPoint {
        x: 128049,
        s: 586575986838176,
    },
    CostLutPoint {
        x: 128855,
        s: 589610325665752,
    },
    CostLutPoint {
        x: 129665,
        s: 592664343553320,
    },
    CostLutPoint {
        x: 130479,
        s: 595738065738812,
    },
    CostLutPoint {
        x: 131298,
        s: 598835301316315,
    },
    CostLutPoint {
        x: 132120,
        s: 601948510672223,
    },
    CostLutPoint {
        x: 132947,
        s: 605085291633016,
    },
    CostLutPoint {
        x: 133777,
        s: 608238080732035,
    },
    CostLutPoint {
        x: 134612,
        s: 611414496774581,
    },
    CostLutPoint {
        x: 135451,
        s: 614610765019198,
    },
    CostLutPoint {
        x: 136294,
        s: 617826905784060,
    },
    CostLutPoint {
        x: 137141,
        s: 621062938694296,
    },
    CostLutPoint {
        x: 137993,
        s: 624322711414501,
    },
    CostLutPoint {
        x: 138849,
        s: 627602424249314,
    },
    CostLutPoint {
        x: 139709,
        s: 630902094658341,
    },
    CostLutPoint {
        x: 140573,
        s: 634221739410258,
    },
    CostLutPoint {
        x: 141442,
        s: 637565224743232,
    },
    CostLutPoint {
        x: 142315,
        s: 640928726451324,
    },
    CostLutPoint {
        x: 143192,
        s: 644312259145276,
    },
    CostLutPoint {
        x: 144074,
        s: 647719702670875,
    },
    CostLutPoint {
        x: 144960,
        s: 651147214732044,
    },
    CostLutPoint {
        x: 145851,
        s: 654598684072641,
    },
    CostLutPoint {
        x: 146746,
        s: 658070256461164,
    },
    CostLutPoint {
        x: 147646,
        s: 661565829424618,
    },
    CostLutPoint {
        x: 148550,
        s: 665081536923274,
    },
    CostLutPoint {
        x: 149459,
        s: 668621285151432,
    },
    CostLutPoint {
        x: 150372,
        s: 672181196393828,
    },
    CostLutPoint {
        x: 151289,
        s: 675761278787137,
    },
    CostLutPoint {
        x: 152212,
        s: 679369362903323,
    },
    CostLutPoint {
        x: 153139,
        s: 682997652095824,
    },
    CostLutPoint {
        x: 154070,
        s: 686646152325574,
    },
    CostLutPoint {
        x: 155006,
        s: 690318795086147,
    },
    CostLutPoint {
        x: 155947,
        s: 694015599473506,
    },
    CostLutPoint {
        x: 156893,
        s: 697736583743179,
    },
    CostLutPoint {
        x: 157843,
        s: 701477824795574,
    },
    CostLutPoint {
        x: 158798,
        s: 705243270306599,
    },
    CostLutPoint {
        x: 159758,
        s: 709032936127681,
    },
    CostLutPoint {
        x: 160723,
        s: 712846837284497,
    },
    CostLutPoint {
        x: 161692,
        s: 716681028826615,
    },
    CostLutPoint {
        x: 162667,
        s: 720543437873119,
    },
    CostLutPoint {
        x: 163646,
        s: 724426154185750,
    },
    CostLutPoint {
        x: 164630,
        s: 728333148788927,
    },
    CostLutPoint {
        x: 165619,
        s: 732264432751544,
    },
    CostLutPoint {
        x: 166613,
        s: 736220016346975,
    },
    CostLutPoint {
        x: 167612,
        s: 740199909058910,
    },
    CostLutPoint {
        x: 168616,
        s: 744204119587483,
    },
    CostLutPoint {
        x: 169625,
        s: 748232655855670,
    },
    CostLutPoint {
        x: 170639,
        s: 752285525015963,
    },
    CostLutPoint {
        x: 171658,
        s: 756362733457296,
    },
    CostLutPoint {
        x: 172682,
        s: 760464286812245,
    },
    CostLutPoint {
        x: 173711,
        s: 764590189964463,
    },
    CostLutPoint {
        x: 174746,
        s: 768744462914857,
    },
    CostLutPoint {
        x: 175785,
        s: 772919081464534,
    },
    CostLutPoint {
        x: 176830,
        s: 777122084053177,
    },
    CostLutPoint {
        x: 177880,
        s: 781349456677718,
    },
    CostLutPoint {
        x: 178935,
        s: 785601200484827,
    },
    CostLutPoint {
        x: 179996,
        s: 789881351971350,
    },
    CostLutPoint {
        x: 181062,
        s: 794185882698365,
    },
    CostLutPoint {
        x: 182133,
        s: 798514791626709,
    },
    CostLutPoint {
        x: 183209,
        s: 802868077044684,
    },
    CostLutPoint {
        x: 184291,
        s: 807249788121359,
    },
    CostLutPoint {
        x: 185379,
        s: 811659933171462,
    },
    CostLutPoint {
        x: 186471,
        s: 816090401496300,
    },
    CostLutPoint {
        x: 187570,
        s: 820553365783345,
    },
    CostLutPoint {
        x: 188673,
        s: 825036643654902,
    },
    CostLutPoint {
        x: 189782,
        s: 829548358499434,
    },
    CostLutPoint {
        x: 190897,
        s: 834088514731424,
    },
    CostLutPoint {
        x: 192018,
        s: 838657115952131,
    },
    CostLutPoint {
        x: 193144,
        s: 843250084188229,
    },
    CostLutPoint {
        x: 194275,
        s: 847867410981231,
    },
    CostLutPoint {
        x: 195412,
        s: 852513175017874,
    },
    CostLutPoint {
        x: 196555,
        s: 857187376967197,
    },
    CostLutPoint {
        x: 197704,
        s: 861890016739421,
    },
    CostLutPoint {
        x: 198858,
        s: 866616995662125,
    },
    CostLutPoint {
        x: 200018,
        s: 871372403389509,
    },
    CostLutPoint {
        x: 201184,
        s: 876156237732664,
    },
    CostLutPoint {
        x: 202356,
        s: 880968495790717,
    },
    CostLutPoint {
        x: 203534,
        s: 885809173962940,
    },
    CostLutPoint {
        x: 204717,
        s: 890674153977258,
    },
    CostLutPoint {
        x: 205907,
        s: 895571655716034,
    },
    CostLutPoint {
        x: 207102,
        s: 900493442538997,
    },
    CostLutPoint {
        x: 208304,
        s: 905447745498170,
    },
    CostLutPoint {
        x: 209511,
        s: 910426314329335,
    },
    CostLutPoint {
        x: 210724,
        s: 915433261792994,
    },
    CostLutPoint {
        x: 211944,
        s: 920472712012246,
    },
    CostLutPoint {
        x: 213170,
        s: 925540529996126,
    },
    CostLutPoint {
        x: 214401,
        s: 930632568479727,
    },
    CostLutPoint {
        x: 215639,
        s: 935757090602343,
    },
    CostLutPoint {
        x: 216883,
        s: 940909950839950,
    },
    CostLutPoint {
        x: 218133,
        s: 946091138191817,
    },
    CostLutPoint {
        x: 219390,
        s: 951304790180403,
    },
    CostLutPoint {
        x: 220653,
        s: 956546751087461,
    },
    CostLutPoint {
        x: 221922,
        s: 961817008256398,
    },
    CostLutPoint {
        x: 223197,
        s: 967115548542051,
    },
    CostLutPoint {
        x: 224479,
        s: 972446517935947,
    },
    CostLutPoint {
        x: 225767,
        s: 977805747849171,
    },
    CostLutPoint {
        x: 227062,
        s: 983197388332254,
    },
    CostLutPoint {
        x: 228363,
        s: 988617264602464,
    },
    CostLutPoint {
        x: 229671,
        s: 994069530690328,
    },
    CostLutPoint {
        x: 230985,
        s: 999550005813382,
    },
    CostLutPoint {
        x: 232306,
        s: 1005062847904248,
    },
    CostLutPoint {
        x: 233633,
        s: 1010603870374097,
    },
    CostLutPoint {
        x: 234967,
        s: 1016177234980825,
    },
    CostLutPoint {
        x: 236308,
        s: 1021782930895098,
    },
    CostLutPoint {
        x: 237656,
        s: 1027420946754501,
    },
    CostLutPoint {
        x: 239010,
        s: 1033087084831981,
    },
    CostLutPoint {
        x: 240371,
        s: 1038785514215757,
    },
    CostLutPoint {
        x: 241738,
        s: 1044512031943562,
    },
    CostLutPoint {
        x: 243113,
        s: 1050275003018286,
    },
    CostLutPoint {
        x: 244494,
        s: 1056066031300757,
    },
    CostLutPoint {
        x: 245883,
        s: 1061893489383894,
    },
    CostLutPoint {
        x: 247278,
        s: 1067748971892238,
    },
    CostLutPoint {
        x: 248680,
        s: 1073636658330874,
    },
    CostLutPoint {
        x: 250089,
        s: 1079556533405372,
    },
    CostLutPoint {
        x: 251506,
        s: 1085512785826764,
    },
    CostLutPoint {
        x: 252929,
        s: 1091496992675813,
    },
    CostLutPoint {
        x: 254360,
        s: 1097517548176140,
    },
    CostLutPoint {
        x: 255797,
        s: 1103566021091365,
    },
    CostLutPoint {
        x: 257242,
        s: 1109650812485488,
    },
    CostLutPoint {
        x: 258694,
        s: 1115767696723790,
    },
    CostLutPoint {
        x: 260154,
        s: 1121920871426132,
    },
    CostLutPoint {
        x: 261620,
        s: 1128101889523035,
    },
    CostLutPoint {
        x: 263094,
        s: 1134319165137269,
    },
    CostLutPoint {
        x: 264576,
        s: 1140572684725455,
    },
    CostLutPoint {
        x: 266064,
        s: 1146853990082851,
    },
    CostLutPoint {
        x: 267560,
        s: 1153171504652341,
    },
    CostLutPoint {
        x: 269064,
        s: 1159525213879554,
    },
    CostLutPoint {
        x: 270575,
        s: 1165910875953814,
    },
    CostLutPoint {
        x: 272094,
        s: 1172332699436989,
    },
    CostLutPoint {
        x: 273620,
        s: 1178786438877451,
    },
    CostLutPoint {
        x: 275154,
        s: 1185276305419809,
    },
    CostLutPoint {
        x: 276696,
        s: 1191802283011668,
    },
    CostLutPoint {
        x: 278245,
        s: 1198360121006393,
    },
    CostLutPoint {
        x: 279802,
        s: 1204954034289584,
    },
    CostLutPoint {
        x: 281367,
        s: 1211584006067219,
    },
    CostLutPoint {
        x: 282940,
        s: 1218250019301044,
    },
    CostLutPoint {
        x: 284521,
        s: 1224952056722783,
    },
    CostLutPoint {
        x: 286109,
        s: 1231685859767855,
    },
    CostLutPoint {
        x: 287705,
        s: 1238455649268232,
    },
    CostLutPoint {
        x: 289310,
        s: 1245265651038322,
    },
    CostLutPoint {
        x: 290922,
        s: 1252107361096767,
    },
    CostLutPoint {
        x: 292543,
        s: 1258989249723888,
    },
    CostLutPoint {
        x: 294171,
        s: 1265902807692451,
    },
    CostLutPoint {
        x: 295808,
        s: 1272856509837956,
    },
    CostLutPoint {
        x: 297453,
        s: 1279846091478648,
    },
    CostLutPoint {
        x: 299106,
        s: 1286871533883028,
    },
    CostLutPoint {
        x: 300767,
        s: 1293932818220839,
    },
    CostLutPoint {
        x: 302437,
        s: 1301034178422003,
    },
    CostLutPoint {
        x: 304115,
        s: 1308171344755791,
    },
    CostLutPoint {
        x: 305802,
        s: 1315348553037812,
    },
    CostLutPoint {
        x: 307497,
        s: 1322561531186286,
    },
    CostLutPoint {
        x: 309200,
        s: 1329810259927075,
    },
    CostLutPoint {
        x: 310912,
        s: 1337098977869739,
    },
    CostLutPoint {
        x: 312632,
        s: 1344423409683911,
    },
    CostLutPoint {
        x: 314361,
        s: 1351787795777111,
    },
    CostLutPoint {
        x: 316099,
        s: 1359192119501205,
    },
    CostLutPoint {
        x: 317845,
        s: 1366632102501806,
    },
    CostLutPoint {
        x: 319600,
        s: 1374111987791278,
    },
    CostLutPoint {
        x: 321364,
        s: 1381631758505331,
    },
    CostLutPoint {
        x: 323137,
        s: 1389191397711581,
    },
    CostLutPoint {
        x: 324918,
        s: 1396786623427617,
    },
    CostLutPoint {
        x: 326709,
        s: 1404425947802318,
    },
    CostLutPoint {
        x: 328508,
        s: 1412100823012046,
    },
    CostLutPoint {
        x: 330317,
        s: 1419819764355011,
    },
    CostLutPoint {
        x: 332134,
        s: 1427574220827697,
    },
    CostLutPoint {
        x: 333961,
        s: 1435372710779877,
    },
    CostLutPoint {
        x: 335796,
        s: 1443206680204716,
    },
    CostLutPoint {
        x: 337641,
        s: 1451084650407640,
    },
    CostLutPoint {
        x: 339495,
        s: 1459002335485945,
    },
    CostLutPoint {
        x: 341359,
        s: 1466963990009623,
    },
    CostLutPoint {
        x: 343231,
        s: 1474961054422790,
    },
    CostLutPoint {
        x: 345113,
        s: 1483002055618172,
    },
    CostLutPoint {
        x: 347005,
        s: 1491086978581357,
    },
    CostLutPoint {
        x: 348906,
        s: 1499211534139929,
    },
    CostLutPoint {
        x: 350816,
        s: 1507375705458269,
    },
    CostLutPoint {
        x: 352736,
        s: 1515583751096237,
    },
    CostLutPoint {
        x: 354665,
        s: 1523831380211965,
    },
    CostLutPoint {
        x: 356605,
        s: 1532127129066122,
    },
    CostLutPoint {
        x: 358554,
        s: 1540462430446055,
    },
    CostLutPoint {
        x: 360512,
        s: 1548837267876615,
    },
    CostLutPoint {
        x: 362481,
        s: 1557260181035945,
    },
    CostLutPoint {
        x: 364459,
        s: 1565722599661430,
    },
    CostLutPoint {
        x: 366447,
        s: 1574228786581661,
    },
    CostLutPoint {
        x: 368445,
        s: 1582778727183191,
    },
    CostLutPoint {
        x: 370453,
        s: 1591372406921020,
    },
    CostLutPoint {
        x: 372471,
        s: 1600009811325489,
    },
    CostLutPoint {
        x: 374500,
        s: 1608695206857547,
    },
    CostLutPoint {
        x: 376538,
        s: 1617420017951511,
    },
    CostLutPoint {
        x: 378586,
        s: 1626188510809105,
    },
    CostLutPoint {
        x: 380645,
        s: 1635004953434455,
    },
    CostLutPoint {
        x: 382714,
        s: 1643865050517244,
    },
    CostLutPoint {
        x: 384794,
        s: 1652773071033888,
    },
    CostLutPoint {
        x: 386884,
        s: 1661724719043222,
    },
    CostLutPoint {
        x: 388984,
        s: 1670719980835353,
    },
    CostLutPoint {
        x: 391095,
        s: 1679763126826653,
    },
    CostLutPoint {
        x: 393216,
        s: 1688849860263936,
    },
];
